language: python

python: 2.7

virtualenv:
    system_site_packages: true

env:
    - OMV_ENGINE=NEST
    - OMV_ENGINE=PyNEST
    #- OMV_ENGINE=PyNN_Brian1
    #- OMV_ENGINE=PyNN_NEURON
    - OMV_ENGINE=PyNN_Nest
    - OMV_ENGINE=jNeuroML_validate

before_install:

    # Requirements for Brian & NEST
    - sudo apt-get install -qq python-numpy python-scipy python-matplotlib python-sympy gsl-bin libgsl0-dev

install:
    
    # Create a small scale network to test for NEST_SLI
    - cd NEST_SLI/test/
    - ./create_small_network_sim.sh
    - ls -alt data
    - cd ../..
    
    # Smaller scale PyNN net to test
    - sed -i -e "s/1., # N_scaling/0.1, # N_scaling/g" PyNN/network_params.py

    # Exit before plotting in PyNEST
    - sed -i -e 's/# Plot a raster/exit() # Plot a raster/g'  PyNEST/example.py 

    # Install OMV

    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation


script:
    - omv all -V

