# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

dist: trusty
sudo: false  

addons:
  apt:
    packages:
       # Requirements for Brian & NEST
    - python-numpy 
    - python-scipy 
    - python-matplotlib 
    - python-sympy
    - python-tables 
    - libreadline6-dev 
    - libncurses5-dev 
    - libgsl0-dev
    - cython
    
    
language: python
python: 2.7

virtualenv:
    system_site_packages: true

env:
    - OMV_ENGINE=NEST
    - OMV_ENGINE=PyNEST
    #- OMV_ENGINE=PyNN_Brian1
    #- OMV_ENGINE=PyNN_NEURON
    - OMV_ENGINE=PyNN_Nest
    - OMV_ENGINE=jNeuroML_validate


install:
    
    # Create a small scale network to test for NEST_SLI
    - cd NEST_SLI/test/
    - ./create_small_network_sim.sh
    - ls -alt data
    - cd ../..
    
    - ./make_tests.sh
    - mkdir PyNN/results

    # Install OMV

    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation


script:
    - omv all -V

