language: python

python: 2.7

virtualenv:
    system_site_packages: true

env:
    - OMV_ENGINE=NEST
    #- OMV_ENGINE=PyNEST
    #- OMV_ENGINE=PyNN_Brian1
    #- OMV_ENGINE=PyNN_NEURON
    #- OMV_ENGINE=PyNN_Nest
    - OMV_ENGINE=jNeuroML_validate

before_install:

    # Requirements for Brian & NEST
    - sudo apt-get install -qq python-numpy python-scipy python-matplotlib python-sympy gsl-bin libgsl0-dev

install:
    - cd NEST_SLI/test/
    - ./create_small_network_sim.sh
    - ls -alt data
    - cd ../..

    # Install OMV

    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation


script:
    - omv all -V

