# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

dist: xenial

addons:
  apt:
    packages:
       # Requirements for Brian & NEST
    - python-numpy 
    - python-scipy 
    - python-matplotlib 
    - python-sympy
    - python-tables 
    - libreadline6-dev 
    - libncurses5-dev 
    - libgsl0-dev
    - cython
    
    
language: python
python: 3.7


env:
    - OMV_ENGINE=NEST
    - OMV_ENGINE=PyNEST:2.18.0   # try a specific version of NEST
    #- OMV_ENGINE=PyNEST:2.20.0   # try a specific version of NEST
    #- OMV_ENGINE=PyNN_Brian1
    #- OMV_ENGINE=PyNN_NEURON
    - OMV_ENGINE=PyNN_Nest
    - OMV_ENGINE=jNeuroML_validate


install:
    
    # Create a small scale network to test for NEST_SLI
    - cd NEST_SLI/test/
    - ./create_small_network_sim.sh
    - ls -alt data
    - cd ../..
    
    - ./make_tests.sh

    # Install OMV

    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation


script:
    - omv all -V
    - omv list -V 

